// src/lib/openai.ts

import type { PageSection } from '../types';

export async function generateText(
  prompt: string,
  options?: {
    apiKey?: string;
    model?: string;
    maxTokens?: number;
    temperature?: number;
  }
): Promise<string> {
  const apiKey = options?.apiKey || import.meta.env.VITE_OPENAI_API_KEY;
  const model = options?.model || 'gpt-3.5-turbo';
  const maxTokens = options?.maxTokens || 128;
  const temperature = options?.temperature ?? 0.7;

  if (!apiKey) {
    throw new Error('Missing OpenAI API key. Set VITE_OPENAI_API_KEY in your environment.');
  }

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: 'You are a helpful assistant for landing page and marketing content.' },
        { role: 'user', content: prompt },
      ],
      max_tokens: maxTokens,
      temperature,
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.error?.message || 'Failed to generate text from OpenAI');
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content?.trim();
  if (!text) throw new Error('No text generated by OpenAI');
  return text;
}

export async function generateImage(
  prompt: string,
  options?: {
    apiKey?: string;
    model?: string;
    size?: string;
    style?: string;
  }
): Promise<string> {
  const apiKey = options?.apiKey || import.meta.env.VITE_OPENAI_API_KEY;
  const model = options?.model || 'dall-e-3';
  const size = options?.size || '1024x1024';
  const style = options?.style || 'vivid';

  if (!apiKey) {
    throw new Error('Missing OpenAI API key. Set VITE_OPENAI_API_KEY in your environment.');
  }

  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      prompt,
      n: 1,
      size,
      ...(model === 'dall-e-3' ? { style } : {}),
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.error?.message || 'Failed to generate image from OpenAI');
  }

  const data = await response.json();
  const imageUrl = data.data?.[0]?.url;
  if (!imageUrl) throw new Error('No image generated by OpenAI');
  return imageUrl;
}

export async function generateSections(
  prompt: string,
  options?: {
    apiKey?: string;
    model?: string;
    maxTokens?: number;
    temperature?: number;
  }
): Promise<PageSection[]> {
  const apiKey = options?.apiKey || import.meta.env.VITE_OPENAI_API_KEY;
  const model = options?.model || 'gpt-3.5-turbo';
  const maxTokens = options?.maxTokens || 1024;
  const temperature = options?.temperature ?? 0.7;

  if (!apiKey) {
    throw new Error('Missing OpenAI API key. Set VITE_OPENAI_API_KEY in your environment.');
  }

  const systemPrompt = `You are an expert landing page builder assistant. Given a product or business description, generate a JSON array of landing page sections. Each section should have: type (one of: hero, features, testimonials, faq, cta, pricing, gallery, video, countdown, contact, newsletter, social, custom), content (object), and styles (object, can be empty). Return ONLY a valid JSON array, no explanation.`;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: prompt },
      ],
      max_tokens: maxTokens,
      temperature,
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.error?.message || 'Failed to generate sections from OpenAI');
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content?.trim();
  if (!text) throw new Error('No sections generated by OpenAI');

  // Try to parse JSON from the response
  try {
    // Find the first and last brackets to extract the JSON array
    const start = text.indexOf('[');
    const end = text.lastIndexOf(']');
    if (start === -1 || end === -1) throw new Error('No JSON array found in AI response');
    const json = text.slice(start, end + 1);
    const sections = JSON.parse(json);
    if (!Array.isArray(sections)) throw new Error('AI did not return an array');
    // Optionally: validate each section has type/content
    return sections;
  } catch {
    throw new Error('Failed to parse AI-generated sections. Try rewording your prompt.');
  }
} 